### ISSUE TITLE
we're babagaboosh

### ISSUE THREAD

**Issue by cubers93** [DougDougGithub/Babagaboosh#11]
![05c](https://github.com/DougDougGithub/Babagaboosh/assets/101417971/06891a0e-8bf1-423d-9867-02d7e5dbecd1)

**Comment by MrManiacc** [comment]
![1692886961898](https://github.com/DougDougGithub/Babagaboosh/assets/4280960/c5aab9ad-4b85-4837-b06e-cf006ab6bfc0)
