### ISSUE TITLE
azure_storage Error / Fix - Got Fixed - check PR 33

### ISSUE THREAD

**Issue by Naraku9929** [DougDougGithub/Babagaboosh#27]
If you are getting the following error:

pip install azure-storage
Defaulting to user installation because normal site-packages is not writeable
Collecting azure-storage
  Using cached azure-storage-0.37.0.zip (4.3 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\****\AppData\Local\Temp\pip-install-sygw9hnm\azure-storage_7f36e5eeaf72445ea4bf307ccce5f4c9\setup.py", line 55, in <module>
          raise RuntimeError(message)
      RuntimeError:
     
      Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
      Please install the service specific packages prefixed by `azure` needed for your application.
     
      The complete list of available packages can be found at:
      https://aka.ms/azsdk/python/all
     
      Here's a non-exhaustive list of common packages:
     
      - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
      - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
      - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

USE: pip install azure-storage-blob

**Comment by wolfmic** [comment]
Oh right. however it seems that there is still something missing:
`import azure.cognitiveservices.speech as speechsdk`

It does not include  that one right ?

[according to this link](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux%2Cubuntu%2Cdotnetcli%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi&pivots=programming-language-python) we should probably install `pip install azure-cognitiveservices-speech`

(meaning adding azure-cognitiveservices-speech as well to requirements.txt)

**Comment by BartoszKak0l** [comment]
Made a PR that fixes it with proof. https://github.com/DougDougGithub/Babagaboosh/pull/33
