### ISSUE TITLE
Actual suggestion: Put each shared python module into its own repository

### ISSUE THREAD

**Issue by qwertychouskie** [DougDougGithub/Babagaboosh#28]
For example, your OBS Websockets code that is shared across your projects should be in its own repository, so that if you make later changes, you don't have to copy those changes to every git repository.

**Comment by PatheticProgrammingPerson** [comment]
DouglasDouglas will not be altering this, you could fork it though, I'm sure there'll be a more active fork at some point, why not *this* point?

**Comment by DougDougGithub** [comment]
I'll probably do this at some point in the future but for now I'd rather have everything bundled into a project that doesn't have external dependencies.
