### ISSUE TITLE
Actual issues that are still happening with the latest push - continuously updated, scroll down to the bottom

### ISSUE THREAD

**Issue by MagmaGuy** [DougDougGithub/Babagaboosh#34]
On a fresh setup, you are still missing the `azure.cognitiveservices` module as also pointed out [here](https://github.com/DougDougGithub/Babagaboosh/issues/27#issuecomment-1890172681).

According to that post you need `pip install azure-cognitiveservices-speech` as well in the requirements.

However, upon installing that, I get a module missing error with pydantic_core, which can also be installed with `pip install pydantic`, although it doesn't seem to have helped.

**Comment by wolfmic** [comment]
May I ask what version of python are you using? 
And what is the complete error?

**Comment by MagmaGuy** [comment]
> May I ask what version of python are you using? And what is the complete error?

The azure cognitiveservices fix is here: https://github.com/DougDougGithub/Babagaboosh/issues/36#issue-2079929056

For pydantic:

```
$ python chatgpt_character.py
Traceback (most recent call last):
  File "C:\Users\~\Downloads\Babagaboosh-main\Babagaboosh-main\chatgpt_character.py", line 5, in <module>
    from openai_chat import OpenAiManager
  File "C:\Users\~\Downloads\Babagaboosh-main\Babagaboosh-main\openai_chat.py", line 1, in <module>
    from openai import OpenAI
  File "C:\Users\~\anaconda3\Lib\site-packages\openai\__init__.py", line 8, in <module>
    from . import types
  File "C:\Users\~\anaconda3\Lib\site-packages\openai\types\__init__.py", line 5, in <module>
    from .image import Image as Image
  File "C:\Users\~\anaconda3\Lib\site-packages\openai\types\image.py", line 5, in <module>
    from .._models import BaseModel
  File "C:\Users\~\anaconda3\Lib\site-packages\openai\_models.py", line 20, in <module>
    from pydantic.fields import FieldInfo
  File "C:\Users\~\anaconda3\Lib\site-packages\pydantic\fields.py", line 21, in <module>
    from pydantic_core import PydanticUndefined
  File "C:\Users\~\anaconda3\Lib\site-packages\pydantic_core\__init__.py", line 6, in <module>
    from ._pydantic_core import (
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'
```

With python 3.11.0, windows 11

**Comment by Randomblock1** [comment]
#40 fixes it, basically to fix installing pydantic you need to force it to use v1 not v2.

**Comment by MagmaGuy** [comment]
> #40 fixes it, basically to fix installing pydantic you need to force it to use v1 not v2.

Now I get

```
$ python openai_chat.py
Traceback (most recent call last):
  File "C:\Users\~\Downloads\Babagaboosh-main (2)\Babagaboosh-main\openai_chat.py", line 1, in <module>
    from openai import OpenAI
  File "C:\Users\~\anaconda3\Lib\site-packages\openai\__init__.py", line 11, in <module>
    from ._client import Client, OpenAI, Stream, Timeout, Transport, AsyncClient, AsyncOpenAI, AsyncStream, RequestOptions
  File "C:\Users\~\anaconda3\Lib\site-packages\openai\_client.py", line 11, in <module>
    from . import resources, _exceptions
  File "C:\Users\~\anaconda3\Lib\site-packages\openai\resources\__init__.py", line 3, in <module>
    from .beta import Beta, AsyncBeta, BetaWithRawResponse, AsyncBetaWithRawResponse
  File "C:\Users\~\anaconda3\Lib\site-packages\openai\resources\beta\__init__.py", line 3, in <module>
    from .beta import Beta, AsyncBeta, BetaWithRawResponse, AsyncBetaWithRawResponse
  File "C:\Users\~\anaconda3\Lib\site-packages\openai\resources\beta\beta.py", line 5, in <module>
    from .threads import Threads, AsyncThreads, ThreadsWithRawResponse, AsyncThreadsWithRawResponse
  File "C:\Users\~\anaconda3\Lib\site-packages\openai\resources\beta\threads\__init__.py", line 3, in <module>
    from .runs import Runs, AsyncRuns, RunsWithRawResponse, AsyncRunsWithRawResponse
  File "C:\Users\~\anaconda3\Lib\site-packages\openai\resources\beta\threads\runs\__init__.py", line 3, in <module>
    from .runs import Runs, AsyncRuns, RunsWithRawResponse, AsyncRunsWithRawResponse
  File "C:\Users\~\anaconda3\Lib\site-packages\openai\resources\beta\threads\runs\runs.py", line 10, in <module>
    from .steps import Steps, AsyncSteps, StepsWithRawResponse, AsyncStepsWithRawResponse
  File "C:\Users\~\anaconda3\Lib\site-packages\openai\resources\beta\threads\runs\steps.py", line 14, in <module>
    from .....pagination import SyncCursorPage, AsyncCursorPage
  File "C:\Users\~\anaconda3\Lib\site-packages\openai\pagination.py", line 6, in <module>
    from ._base_client import BasePage, PageInfo, BaseSyncPage, BaseAsyncPage
  File "C:\Users\~\anaconda3\Lib\site-packages\openai\_base_client.py", line 36, in <module>
    import anyio
ModuleNotFoundError: No module named 'anyio'
```

**Comment by MagmaGuy** [comment]
To be clear, this is with the latest update of this repo, not of #40 which I think was meant to be merged.

**Comment by MagmaGuy** [comment]
# Issues:

- Missing module `anyio`
- Missing `TestAudio_MP3.mp3` which `audio_player.py` seems to try to run and error when it doesn't find it

**Comment by MagmaGuy** [comment]
Pretty sure he meant to merge #44 at the end of the stream but didn't actually do it

**Comment by MagmaGuy** [comment]
As of #44 - keyboard module is missing

```
Traceback (most recent call last):
  File "C:\Users\~\Downloads\Babagaboosh-main\Babagaboosh-main\chatgpt_character.py", line 2, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'

```

Also, thanks for that readme update.

# Issues:
- Keyboard module is missing

**Comment by BartoszKak0l** [comment]
> As of #44 - keyboard module is missing
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\~\Downloads\Babagaboosh-main\Babagaboosh-main\chatgpt_character.py", line 2, in <module>
>     import keyboard
> ModuleNotFoundError: No module named 'keyboard'
> ```
> 
> Also, thanks for that readme update.
> 
> # Issues:
> * Keyboard module is missing

Make sure you installed requirements.txt as it is specified in there.  `pip install - r requirements.txt`

**Comment by MagmaGuy** [comment]
> > As of #44 - keyboard module is missing
> > ```
> > Traceback (most recent call last):
> >   File "C:\Users\~\Downloads\Babagaboosh-main\Babagaboosh-main\chatgpt_character.py", line 2, in <module>
> >     import keyboard
> > ModuleNotFoundError: No module named 'keyboard'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, thanks for that readme update.
> > # Issues:
> > 
> > * Keyboard module is missing
> 
> Make sure you installed requirements.txt as it is specified in there. `pip install - r requirements.txt`

I did, I've been doing it every single time there's been an update

**Comment by MagmaGuy** [comment]
To be clear, this shows up when running the requirements:

`Requirement already satisfied: keyboard==0.13.5 in c:\users\~\anaconda3\lib\site-packages (from -r requirements.txt (line 4)) (0.13.5)`

**Comment by BartoszKak0l** [comment]
I would try `pip uninstall -r requirements.txt` and install again. Alternatively you can just directly call `pip uninstall keyboard` and `pip install keyboard`. Python can be a mess sometimes with many interpreters and stuff.

**Comment by MagmaGuy** [comment]
> I would try `pip uninstall -r requirements.txt` and install again. Alternatively you can just directly call `pip uninstall keyboard` and `pip install keyboard`. Python can be a mess sometimes with many interpreters and stuff.

Just ran the uninstall, removed everything in requirements and installed it again. Same `keyboard` issue. I am trying to provide a clean setup here that would be representative of what a fresh user on a fresh install would experience, if I fix the issue for myself it won't fix it for others

**Comment by BartoszKak0l** [comment]
I get it. Honestly the instructions didn't suggest setting up venv to isolate global interpreter which is kinda asking for package errors with python. I use pycharm which automatically set up venv for me and installed/resolved keyboard module without an issue after installing requirements :/ Seems to me like you have another copy of the package somewhere on your machine in a different interpreter and pip doesn't want to install it correctly now. How it ended up there in the first place though is a mystery to me.

**Comment by MagmaGuy** [comment]
Yeah, I have pycharm as well but I am just trying to stick to the instructions,  I've already made a chatgpt frontend in python before so I could probably fix it for my install but I just came here to accurately report potential issues with the default methodology. Once I do have it all up and running using all defaults I might submit some pull requests for QOL stuff.

**Comment by MagmaGuy** [comment]
Woah there, hold up. I was idly looking at the readme and I noticed it was recommending `python3 chatgpt_character.py` which I was using. Decided to try `python chatgpt_character.py` instead and that seems to work, at least it finally realized I haven't added any API keys yet

**Comment by DougDougGithub** [comment]
Checking that these issues are all resolved now?

**Comment by MagmaGuy** [comment]
> Checking that these issues are all resolved now?

It would seem that as long as you don't recommend to run python3 and instead run python it worked on my setup.

**Comment by Randomblock1** [comment]
That's probably because you have multiple Python versions installed. For some reason python and python3 can point to different installs, you just need to make sure that you use pip or pip3 depending on which you're using. If you only have 1 Python version installed it won't matter and you can use them interchangeably

**Comment by MagmaGuy** [comment]
> That's probably because you have multiple Python versions installed. For some reason python and python3 can point to different installs, you just need to make sure that you use pip or pip3 depending on which you're using. If you only have 1 Python version installed it won't matter and you can use them interchangeably

I understand that but odds are it would've been more ideal to run this in a self-contained environment, because I doubt I'm the only person running more than one python version.. I've never worked that much with python but I believe things like conda achieve this, though I understand why this project does not operate under those circumstances, given the context within which it exists.

**Comment by DougDougGithub** [comment]
Yep it sounds like it's due to what version of python you're running. If other folks are running into this, just make sure you're running Python 3.9.2, and/or run it in a self-contained environment. I don't personally know how to do that (that's more complexity than I'd like to get into) but agree it sounds like the best approach to avoid something like this and I encourage others to try doing that. I'm closing this for now since the issues are technically resolved, can open up a new issue as needed
