### ISSUE TITLE
Again, push didn't work.

### ISSUE THREAD

**Issue by MagmaGuy** [DougDougGithub/Babagaboosh#36]
Now your requirements.txt gives this error:

```
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech==12.19.0 (from versions: 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.25.1b1, 1.26.0, 1.27.0, 1.28.0, 1.29.0, 1.30.0, 1.31.0, 1.32.1, 1.33.0, 1.34.0)
ERROR: No matching distribution found for azure-cognitiveservices-speech==12.19.0
```

Fairly self-explanatory!

**Comment by BartoszKak0l** [comment]
I was stupid and rushed and forgot to update hardcoded version sorry :/ https://github.com/DougDougGithub/Babagaboosh/pull/37

**Comment by MagmaGuy** [comment]
> I was stupid and rushed and forgot to update hardcoded version sorry :/ #37

well let's find a way to get him to read this. 1.34.0 should work?

**Comment by BartoszKak0l** [comment]
yeah I tried posting in chat.

**Comment by MagmaGuy** [comment]
> yeah I tried posting in chat.

Any idea about the other issue I reported about pydantic_core._pydantic_core not working?

Also, I think TestAudio_MP3.mp3 should've probably been included in this project

**Comment by MagmaGuy** [comment]
Closing this one to centralize my issues in #34
