### ISSUE TITLE
Help please - Fixed in last push!!

### ISSUE THREAD

**Issue by drago5212** [DougDougGithub/Babagaboosh#39]
getting this- i have done everything from the fixes but keep getting this even under a fresh install

Exception has occurred: PydanticUserError
If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.5/u/root-validator-pre-skip
  File "C:\Users\***\Desktop\Babagaboosh-main\eleven_labs.py", line 1, in <module>
    from elevenlabs import generate, stream, set_api_key, voices, play, save
  File "C:\Users\*****\Desktop\Babagaboosh-main\chatgpt_character.py", line 6, in <module>
    from eleven_labs import ElevenLabsManager
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.5/u/root-validator-pre-skip

**Comment by Randomblock1** [comment]
Install pydantic v1 not v2, should be fixed by #40 which just got merged.

**Comment by MagmaGuy** [comment]
If it's fixed please close, I think odds are very slim that someone will actually look at these and close them for you.
