### ISSUE TITLE
More bald?

### ISSUE THREAD

**Issue by alwavshumilin** [DougDougGithub/Babagaboosh#4]
I mean, the author is already bald, but I feel like it’s not enough. Please fix, THX <3

**Comment by wolfmic** [comment]
probably a duplicate of #1

**Comment by alwavshumilin** [comment]
Yeah, but dropping static refs is not enough either. We might experience pointers overload, hence something must be done on the low level

**Comment by MrManiacc** [comment]
@DougDougGithub this is a duplicate of #1 can we close this issue?
