### ISSUE TITLE
Chat GPT to TTS issues

### ISSUE THREAD

**Issue by drago5212** [DougDougGithub/Babagaboosh#45]
So got everything working but when it goes to translate what chat GPT said it comes up with this error

Exception has occurred: ValueError
Voice 'Pointboat' not found.
  File "C:\Users\*****\Desktop\Babagaboosh-main\eleven_labs.py", line 19, in text_to_audio
    audio_saved = generate(
  File "C:\Users\***\Desktop\Babagaboosh-main\chatgpt_character.py", line 62, in <module>
    elevenlabs_output = elevenlabs_manager.text_to_audio(openai_result, "Pointboat", False)
ValueError: Voice 'Pointboat' not found.

**Comment by BartoszKak0l** [comment]
If I remember correctly from the stream in elevnlabs you create custom voices using audio sample and the Pointboat is name of one of Doug's custom voices he made using Pointcrow's and Failboat's audio samples. Guess you need to create your own model and change the name string or call it the same

**Comment by drago5212** [comment]
alright will give it a go haha

**Comment by DougDougGithub** [comment]
Yep that's correct, you will need to replace that with a voice that you've made on the Elevenlabs website, "Pointboat" is one of the voices I've made but it's not publicly available. Forgot to mention that in the video explanation
