### ISSUE TITLE
TypeError on elevenlabs.py

### ISSUE THREAD

**Issue by Drapperbat** [DougDougGithub/Babagaboosh#49]
Line 19 of elevenlabs.py is being highlighted with this error after submitting voice inputs:

Exception has occurred: TypeError
list indices must be integers or slices, not str
  File "C:\Users\---\Babagaboosh-main\eleven_labs.py", line 19, in text_to_audio
    audio_saved = generate(
  File "C:\Users\---\Babagaboosh-main\chatgpt_character.py", line 62, in <module>
    elevenlabs_output = elevenlabs_manager.text_to_audio(openai_result, ELEVENLABS_VOICE, False)
TypeError: list indices must be integers or slices, not str

Really gave learning python my best shot for the sake of this cool project and managed to make it pretty far but after about 3 hours I have to admit defeat and ask if anyone knows a fix for this

**Comment by Drapperbat** [comment]
Discovered that this error only occurs when you record very short messages for ChatGPT

**Comment by officialjakefromstatefarm** [comment]
Skill issue, Doug's code is clearly the greatest of all time.

**Comment by Jonpatty** [comment]
I have also been having this issue, if anyone finds a fix, please let me know.

**Comment by DougDougGithub** [comment]
Could you provide an example of what ChatGPT prompt is causing this issue? Like what specifically causes the error to happen, since I have not seen this before

**Comment by Jonpatty** [comment]
Not really sure what is causing it, I didn't edit the prompt from what you put in the code, I changed the voice to what I got in Elevenlabs, and I know my Azure API key is okay as it works with the chatgod code.

**Comment by Jonpatty** [comment]
Azure is under "Speech" too, it tells me input not recognised also.

**Comment by Jonpatty** [comment]
Ending azure speech recognition



Heres the result we got!




Didn't receive input!
RECOGNIZED: SpeechRecognitionEventArgs(session_id=4878b4a110164f80a637ab6ed0423546, result=SpeechRecognitionResult(result_id=06b659d2e6084bb684580a1c4aa64bb0, text="", reason=ResultReason.RecognizedSpeech))
CLOSING speech recognition on SessionEventArgs(session_id=4878b4a110164f80a637ab6ed0423546)
Traceback (most recent call last):
  File "c:\Users\jonpa\Downloads\Python\AIs\Babagaboosh-main\chatgpt_character.py", line 64, in <module>
    elevenlabs_output = elevenlabs_manager.text_to_audio(openai_result, ELEVENLABS_VOICE, False)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jonpa\Downloads\Python\AIs\Babagaboosh-main\eleven_labs.py", line 19, in text_to_audio
    audio_saved = generate(
                  ^^^^^^^^^
  File "C:\Users\jonpa\Downloads\Python\AIs\Babagaboosh-main\.venv\Lib\site-packages\elevenlabs\simple.py", line 86, in generate    assert isinstance(text, str)
AssertionError

Here are the full logs I get for you.

**Comment by DougDougGithub** [comment]
Based on that error it looks like you're not actually recording anything from your microphone. That's why it says:
"Didn't receive input!"
The app will listen to your PC's default microphone, so this means that either (1) your PC's current microphone isn't actually picking up audio for whatever reason, or (2) you didn't wait long enough for Azure to listen to what you were saying before you pressed P and told it you were done. Most likely this is a microphone setting issue you'd need to sort out on your end, but I'll add some code in the future that gives more info if no microphone input is received, rather than just crashing the program

**Comment by Jonpatty** [comment]
Hey Doug, thank you for letting me know the issue.
I changed my default microphone in the windows control panel, all works okay now!
Thank you again.

**Comment by fily-gif** [comment]
> Hey Doug, thank you for letting me know the issue. I changed my default microphone in the windows control panel, all works okay now! Thank you again.

close the issue then
