### ISSUE TITLE
Remove Pajama Sam image to avoid DMCA Copyright Takedown

### ISSUE THREAD

**Issue by exurd** [DougDougGithub/Babagaboosh#50]
On the Humongous Entertainment's [Terms and Conditions](https://www.humongous.com/terms-and-conditions#:~:text=Images%20are%20either%20the%20property%20of%2C%20or%20used%20with%20permission%20by%2C%20Humongous%20Entertainment%20The%20use%20of%20these%20images%20by%20you%2C%20or%20anyone%20else%20authorized%20by%20you%2C%20is%20prohibited%20unless%20specifically%20permitted%20by%20these%20Terms%20and%20Conditions.%20Any%20unauthorized%20use%20of%20the%20images%20may%20violate%20copyright%20laws), quote:
> Images are either the property of, or used with permission by, Humongous Entertainment. The use of these images by you, or anyone else authorized by you, is prohibited unless specifically permitted by these Terms and Conditions. **Any unauthorized use of the images may violate copyright laws**, trademark laws, the laws of privacy and publicity, and communications regulations and statutes.

Through GitHub's [DMCA Takedown Policy](https://docs.github.com/en/site-policy/content-removal-policies/dmca-takedown-policy), they can file a report due to the repo using an image of Pajama Sam.
GitHub won't disable the entire repo when they attempt this, as it is only a single file. However, they only give [1 business day for the repo owner](https://docs.github.com/en/site-policy/content-removal-policies/dmca-takedown-policy#what-is-the-dmca:~:text=Otherwise%2C%20because%20GitHub%20cannot%20disable%20access%20to%20specific%20files%20within%20a%20repository%2C%20we%20will%20contact%20the%20user%20who%20created%20the%20repository%20and%20give%20them%20approximately%201%20business%20day%20to%20delete%20or%20modify%20the%20content%20specified%20in%20the%20notice.) to delete the file from the repository and remedy the situation. If the content is not removed by then, GitHub will disable access to the repository.

I recommend removing the infringing content (or replacing it with a well-known public-domain character with mouse ears and a steamboat hat) before the copyright owners choose to send a DMCA takedown.
Although, an ye harm none, do as ye will.

**Comment by fily-gif** [comment]
Pajama Willy

**Comment by officialjakefromstatefarm** [comment]
Pajama Sam: the revenge

**Comment by exurd** [comment]
...hello dougdoug. i hope that this coincides with your secret rule. signed, exurd.

**Comment by DougDougGithub** [comment]
Done
