### ISSUE TITLE
Speech recognition doesnt work :(

### ISSUE THREAD

**Issue by DevGrishin** [DougDougGithub/Babagaboosh#55]
Here is what happens:
CLOSING speech recognition on SpeechRecognitionCanceledEventArgs(session_id=a7c4bbcbe3714869b19b636cbd8ed2c3, result=SpeechRecognitionResult(result_id=5e6c08f125544f29b008796a77ccb583, text="", reason=ResultReason.Canceled))
CLOSING speech recognition on SessionEventArgs(session_id=a7c4bbcbe3714869b19b636cbd8ed2c3)

can anyone help?

**Comment by DevGrishin** [comment]
never mind, i  fixed it by making a new speech project in azure

**Comment by InspiredPom** [comment]
Hey @GGCoder098 , was there anything specifically different on the new project? Running into the same issue across two different projects.

**Comment by InspiredPom** [comment]
It worked the third time, honestly not sure why either.
